### ISSUE TITLE
TLS-E Traceback

### ISSUE THREAD

**Issue by mbaldessari** [luis5tb/bgp-agent#1]
Heya Luis,

just to not lose track of this one. On a TLS-E env I see the following traceback with the agent:
```
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent Traceback (most recent call last):
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/bin/bgp-agent", line 10, in <module>
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     sys.exit(start())
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/lib/python3.6/site-packages/bgp_agent/agent.py", line 76, in start
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     bgp_agent_launcher = service.launch(config.CONF, BGPAgent())
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/lib/python3.6/site-packages/bgp_agent/agent.py", line 45, in __init__
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     CONF.driver)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/lib/python3.6/site-packages/bgp_agent/platform/driver_api.py", line 28, in get_insta
nce
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     invoke_on_load=True
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/stevedore/driver.py", line 62, in __init__
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     warn_on_missing_entrypoint=warn_on_missing_entrypoint
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/stevedore/named.py", line 81, in __init__
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     verify_requirements)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/stevedore/extension.py", line 233, in _load_plugins
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     self._on_load_failure_callback(self, ep, err)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/stevedore/extension.py", line 225, in _load_plugins
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     verify_requirements,
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/stevedore/named.py", line 158, in _load_one_plugin
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     verify_requirements,
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/stevedore/extension.py", line 257, in _load_one_plugin
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     obj = plugin(*invoke_args, **invoke_kwds)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/lib/python3.6/site-packages/bgp_agent/platform/osp/ovn_driver.py", line 66, in __ini
t__
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     events=events)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/lib/python3.6/site-packages/bgp_agent/platform/osp/utils/ovn.py", line 46, in __init
__
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     helper = self._get_ovsdb_helper(connection_string)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/local/lib/python3.6/site-packages/bgp_agent/platform/osp/utils/ovn.py", line 61, in _get_o
vsdb_helper
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     return idlutils.get_schema_helper(connection_string, self.SCHEMA)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/ovsdbapp/backend/ovs_idl/idlutils.py", line 183, in get_schema
_helper
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     stream.Stream.open(c))
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib64/python3.6/site-packages/ovs/stream.py", line 192, in open
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     error, sock = cls._open(suffix, dscp)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib64/python3.6/site-packages/ovs/stream.py", line 795, in _open
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     ctx.use_privatekey_file(Stream._SSL_private_key_file)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 985, in use_privatekey_file
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     keyfile = _path_string(keyfile)
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent   File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 107, in path_string
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent     raise TypeError("Path must be represented as bytes or unicode string")
/var/log/containers/stdouts/bgp_agent.log:2021-03-17T14:54:37.922802270+00:00 stdout F 2021-03-17 14:54:37.918 1 ERROR bgp-agent TypeError: Path must be represented as bytes or unicode string
```

**Comment by luis5tb** [comment]
Fixed at https://github.com/luis5tb/bgp-agent/commit/97295103311004afd0f864fa96941c119d7625bb
